feat: re-added related article component
pricefx/pricefx-eds pull request #53
Opened 2024-04-17 09:52 UTC by mayur-satav

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:

- Before: https://main--pricefx-eds--pricefx.hlx.live/
- After: https://feature-pai-21-be-related-articles--pricefx-eds--pricefx.hlx.live/

2024-04-17 14:14 UTC, amogh-daryapurkar commented on component-definition.json
> +          "title": "Related Article",
@mayur-satav Can we change this to Related Articles instead?

2024-04-17 14:14 UTC, amogh-daryapurkar commented on component-definition.json
> +          "id": "relatedArticle",
@mayur-satav Can we change this to Related Articles instead?

2024-04-17 14:14 UTC, amogh-daryapurkar commented on component-filters.json
> +      "relatedArticle"
@mayur-satav Can we change this to relatedArticles instead?

2024-04-17 14:14 UTC, amogh-daryapurkar commented on component-models.json
> +    "id": "relatedArticle",
@mayur-satav Can we change this to relatedArticles instead?

2024-04-18 07:33 UTC, muneeskumar-rajendran submitted a review, later dismissed

2024-04-22 06:57 UTC, amogh-daryapurkar requested changes

2024-04-22 09:56 UTC, amogh-daryapurkar approved these changes

2024-04-22 09:56 UTC, merged